In [62]:
vuosi=2022

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [3]:
# Load the data frames


perus_df = pd.read_excel("../input/Koulujen_perustiedot_suojattu_200922.xlsx",engine='openpyxl')
toiminta_df = pd.read_excel("../input/Koulujen_toimintasuunnitelmat_suojattu_2022-2023.xlsx",engine="openpyxl")
ktk_df = pd.read_excel("../input/KTK2023-45luokka-suojattu.xlsx",engine="openpyxl")

In [27]:
liitu_kannustajat_df = pd.read_excel("../input/LIITU2022-suojattu-kannustajat.xlsx",engine="openpyxl")
liitu_kouluymp_df = pd.read_excel("../input/LIITU2022-suojattu-kouluymp.xlsx",engine="openpyxl")
liitu_kouluymp2_df = pd.read_excel("../input/LIITU2022_suojattu-kouluymp2.xlsx",engine="openpyxl")
liitu_liikku_df = pd.read_excel("../input/LIITU2022-suojattu-liikkuminen.xlsx",engine="openpyxl")

In [99]:
#liitu_kannustajat_df.Table.value_counts()
#liitu_kouluymp_df.Muuttuja.value_counts()
#liitu_kouluymp2_df.Table.value_counts()

In [11]:
# LIITU Kouluympäristökysely pivotointi

liitu_kouluymp_df.sample(3)

,Koulu_ID,Muuttuja,Vastausvaihtoehdot,Frequency,RowPercent,RowStdErr,RowLowerCL,RowUpperCL
668,137.0,Koulun piha-aluetta ja lähiympäristöä hyödynne...,Ei,9,17.307692,5.249860,7.001067,27.614317
718,188.0,Koulun piha-aluetta ja lähiympäristöä hyödynne...,En osaa sanoa,4,16.666667,7.612466,1.721728,31.611605
534,124.0,Koulun liikuntasali on käytössä välituntiliikk...,En osaa sanoa,8,8.988764,3.033097,3.037905,14.939623

In [107]:
df = pd.DataFrame(liitu_kouluymp_df.drop_duplicates(['Koulu_ID','Muuttuja','Vastausvaihtoehdot'])).fillna('0')
df.Koulu_ID=df.Koulu_ID.astype(int)
df.rename(columns={'Vastausvaihtoehdot':'Vastaus'},inplace=True)
df.Muuttuja = df.Muuttuja.str.replace(r'\s+\(.*','',regex=True)
df = df[(df.Vastaus != 'Total') & (df.Koulu_ID>0)]
df.RowPercent = df.RowPercent.astype(float).round(1)

liitu_ymp1 = df.pivot(columns=['Vastaus'],index=['Koulu_ID','Muuttuja'],values='RowPercent')
liitu_ymp1['vuosi'] = vuosi


# Saving to data folder
liitu_ymp1.to_csv("../data/liitu_kouluymp1.csv")

# Sample rows
liitu_ymp1.head(15)

Vastaus                                                        Ei  \
Koulu_ID Muuttuja
101      Jokaiseen koulupäivään sisältyy vähintään 30 mi...  48.6
         Koululla on liikunnallista kerhotoimintaa           17.6
         Koululla on toimivat polkupyörien ja kypärien s...  20.0
         Koulun liikuntasali on käytössä välituntiliikku...  62.9
         Koulun piha-aluetta ja lähiympäristöä hyödynnet...  14.3
         Koulun pihalla on pelialue ja riittävästi muita...   5.7
         Koulussa kannustetaan oppilaita liikkumaan koul...  35.3
         Koulussa on käytössä koulupyöriä, joita voidaan...  71.4
         Koulussa on riittävästi välituntivälineitä          28.6
         Oppilaat ohjaavat muita oppilaita välituntiliik...  48.6
         Oppitunneilla tauotetaan istumista päivittäin       62.9
         Välituntivälineet ovat kaikkien saatavilla          20.0
102      Jokaiseen koulupäivään sisältyy vähintään 30 mi...  40.0
         Koululla on liikunnallista kerhotoimintaa           13.3
         Koululla on toimivat polkupyörien ja kypärien s...  33.3

Vastaus                                                      En osaa sanoa  \
Koulu_ID Muuttuja
101      Jokaiseen koulupäivään sisältyy vähintään 30 mi...           34.3
         Koululla on liikunnallista kerhotoimintaa                    70.6
         Koululla on toimivat polkupyörien ja kypärien s...           48.6
         Koulun liikuntasali on käytössä välituntiliikku...           31.4
         Koulun piha-aluetta ja lähiympäristöä hyödynnet...           37.1
         Koulun pihalla on pelialue ja riittävästi muita...           45.7
         Koulussa kannustetaan oppilaita liikkumaan koul...           50.0
         Koulussa on käytössä koulupyöriä, joita voidaan...           25.7
         Koulussa on riittävästi välituntivälineitä                   48.6
         Oppilaat ohjaavat muita oppilaita välituntiliik...           51.4
         Oppitunneilla tauotetaan istumista päivittäin                25.7
         Välituntivälineet ovat kaikkien saatavilla                   37.1
102      Jokaiseen koulupäivään sisältyy vähintään 30 mi...           33.3
         Koululla on liikunnallista kerhotoimintaa                    66.7
         Koululla on toimivat polkupyörien ja kypärien s...           40.0

Vastaus                                                      Kyllä  vuosi
Koulu_ID Muuttuja
101      Jokaiseen koulupäivään sisältyy vähintään 30 mi...   17.1   2022
         Koululla on liikunnallista kerhotoimintaa            11.8   2022
         Koululla on toimivat polkupyörien ja kypärien s...   31.4   2022
         Koulun liikuntasali on käytössä välituntiliikku...    5.7   2022
         Koulun piha-aluetta ja lähiympäristöä hyödynnet...   48.6   2022
         Koulun pihalla on pelialue ja riittävästi muita...   48.6   2022
         Koulussa kannustetaan oppilaita liikkumaan koul...   14.7   2022
         Koulussa on käytössä koulupyöriä, joita voidaan...    2.9   2022
         Koulussa on riittävästi välituntivälineitä           22.9   2022
         Oppilaat ohjaavat muita oppilaita välituntiliik...    0.0   2022
         Oppitunneilla tauotetaan istumista päivittäin        11.4   2022
         Välituntivälineet ovat kaikkien saatavilla           42.9   2022
102      Jokaiseen koulupäivään sisältyy vähintään 30 mi...   26.7   2022
         Koululla on liikunnallista kerhotoimintaa            20.0   2022
         Koululla on toimivat polkupyörien ja kypärien s...   26.7   2022

In [1]:
liitu_ymp1

NameError: name 'liitu_ymp1' is not defined

In [139]:
liitu_ymp1.columns

Index(['Ei', 'En osaa sanoa', 'Kyllä', 'vuosi'], dtype='object', name='Vastaus')

In [ ]:
liitu_kouluymp2_df.sample(5)

In [114]:
liitu_kouluymp2_df.groupby(['Table','Vastausvaihtoehdot']).RowPercent.mean()

Table                                                                                                                                                                                                                                                            Vastausvaihtoehdot
Kuinka usein käytät alla olevia paikkoja liikkumiseen kouluajan ulkopuolella vapaa-aikanasi? Laita yksi ruksi ruutuun jokaiselle vaakariville vaikka et käytäkään liikuntapaikkaa:Koulun piha-alue                                                               En käytä laisinkaan                                   25.891679
                                                                                                                                                                                                                                                                 Muutaman kerran kuukaudessa                           20.180544
                                                                                                                                                                                                                                                                 Muutaman kerran vuodessa                              24.314664
                                                                                                                                                                                                                                                                 Noin kerran viikossa                                  16.982562
                                                                                                                                                                                                                                                                 Total                                                100.000000
                                                                                                                                                                                                                                                                 Useita kertoja viikossa                               26.007318
Missä määrin seuraavat tekijät estävät sinun liikunnan ja urheilun harrastamista?:Koululiikunta ei innosta minua.                                                                                                                                                Ei estä lainkaan                                      57.113569
                                                                                                                                                                                                                                                                 Estää erittäin paljon                                 24.718071
                                                                                                                                                                                                                                                                 Estää jonkin verran                                   30.919303
                                                                                                                                                                                                                                                                 Estää paljon                                          11.333762
                                                                                                                                                                                                                                                                 Estää vain vähän                                      15.651644
                                                                                                                                                                                                                                                                 Total                                                100.000000
Missä olet yleensä koulun välitunneilla? Valitse itsellesi sopivin vaihtoehto.                                                                                                                                                                                   Enimmäkseen sisällä, mutta silloin tällöin ulkona     18.237277
                                                                                                                                                                                                                                                                 Enimmäkseen ulkona, mutta silloin tällöin sisällä     29.464478
                                                                                                                                                                                                                                                                 Kaikki välitunnit sisällä                             21.709190
                                                                                                                                                                                                                                                                 Kaikki välitunnit ulkona                              70.020081
                                                                                                                                                                                                                                                                 Total                                                100.000000
Oletko osallistunut seuraaviin koulusi toimintoihin?:Koulun tilojen ja piha-alueiden suunnittelu                                                                                                                                                                  En                                                   76.987959
                                                                                                                                                                                                                                                                 Kyllä                                                 28.721330
                                                                                                                                                                                                                                                                 Total                                                100.000000
Oletko osallistunut seuraaviin koulusi toimintoihin?:Välituntiliikunnan ohjaaminen muille oppilaille                                                                                                                                                              En                                                   80.405127
                                                                                                                                                                                                                                                                 Kyllä                                                 22.394141
                                                                                                                                                                                                                                                                 Total                                                100.000000
Oletko osallistunut seuraaviin koulusi toimintoihin?:Välituntitoiminnan suunnittelu                                                                                                                                                                               En                                                   79.534258
                                                                                                                                                                                                                                                                 Kyllä                                                 23.256525
                                                                                                                                                                                                                                                                 Total                                                100.000000
Seuraavassa tiedustellaan osallistumistasi erilaisiin liikunta- ja urheilutilaisuuksiin.Vastaa jokaiseen vaakarivin kohtaan. Kuinka usein siis liikut vapaa-aikanasi?:Koulussa oppituntien jälkeen pidettävissä liikuntakerhoissa  (koulun oppitunteja ei laske  2-3 päivänä viikossa                                  11.973085
                                                                                                                                                                                                                                                                 4-5 päivänä viikossa                                   6.978970
                                                                                                                                                                                                                                                                 6-7 päivänä viikossa                                   6.420221
                                                                                                                                                                                                                                                                 Harvemmin kuin kerranviikossa tai en lainkaan         70.249616
                                                                                                                                                                                                                                                                 Total                                                100.000000
                                                                                                                                                                                                                                                                 Yhtenä päivänä viikossa                               13.041024
Name: RowPercent, dtype: float64

In [128]:
df = pd.DataFrame(liitu_kouluymp2_df.drop_duplicates(['Koulu_ID','Table','Vastausvaihtoehdot'])).fillna('0')
df.Koulu_ID=df.Koulu_ID.astype(int)
df.rename(columns={'Vastausvaihtoehdot':'Vastaus','Table':'Kysymys'},inplace=True)
df.Kysymys = df.Kysymys.str.replace(r'.*\?\:','',regex=True)
df.Kysymys = df.Kysymys.str.replace(r' Laita.*','',regex=True)
df.Kysymys = df.Kysymys.str.replace(r' Valitse.*','',regex=True)
df.Kysymys = df.Kysymys.str.replace(r' \(.*','',regex=True)
df = df[(df.Vastaus != 'Total') & (df.Koulu_ID>0)]
df.RowPercent = df.RowPercent.astype(float).round(1)

liitu_ymp2 = df.pivot(columns=['Kysymys','Vastaus'],index=['Koulu_ID'],values='RowPercent')
liitu_ymp2['vuosi'] = vuosi

# Saving to data folder
liitu_ymp2.to_csv("../data/liitu_kouluymp2.csv")

# Sample rows
liitu_ymp2.head(10)

Kysymys  Kuinka usein käytät alla olevia paikkoja liikkumiseen kouluajan ulkopuolella vapaa-aikanasi?  \
Vastaus                                                                           En käytä laisinkaan
Koulu_ID
101                                                    27.8
102                                                    26.7
104                                                    50.0
106                                                     0.0
111                                                     NaN
112                                                    20.0
115                                                    25.0
117                                                     NaN
119                                                    12.5
121                                                     NaN

Kysymys                                                        \
Vastaus  Muutaman kerran vuodessa Muutaman kerran kuukaudessa
Koulu_ID
101                          22.2                        11.1
102                          26.7                         6.7
104                           0.0                         0.0
106                         100.0                         0.0
111                           NaN                         NaN
112                          10.0                        40.0
115                           0.0                        50.0
117                           NaN                         NaN
119                           6.2                        50.0
121                           NaN                         NaN

Kysymys                                                \
Vastaus  Noin kerran viikossa Useita kertoja viikossa
Koulu_ID
101                      25.0                    13.9
102                      26.7                    13.3
104                      50.0                     0.0
106                       0.0                     0.0
111                       NaN                     NaN
112                      10.0                    20.0
115                      25.0                     0.0
117                       NaN                     NaN
119                      18.8                    12.5
121                       NaN                     NaN

Kysymys  Koulussa oppituntien jälkeen pidettävissä liikuntakerhoissa   \
Vastaus                 Harvemmin kuin kerranviikossa tai en lainkaan
Koulu_ID
101                                                    77.8
102                                                    80.0
104                                                    44.7
106                                                   100.0
111                                                    48.5
112                                                    89.7
115                                                    47.8
117                                                    41.2
119                                                    72.2
121                                                    76.9

Kysymys                                                                     \
Vastaus  Yhtenä päivänä viikossa 2-3 päivänä viikossa 4-5 päivänä viikossa
Koulu_ID
101                          5.6                 11.1                  5.6
102                          0.0                 13.3                  6.7
104                          2.6                 18.4                 13.2
106                          0.0                  0.0                  0.0
111                         24.2                 21.2                  6.1
112                          3.4                  3.4                  0.0
115                         26.1                 13.0                 13.0
117                         41.2                 11.8                  5.9
119                          8.3                 13.9                  5.6
121                         23.1                  0.0                  0.0

Kysymys                        ...  \
Vastaus  6-7 päivänä viikossa  ...
Koulu_ID                       ...
101                       0.0  ...
102                       0.0  ...
104                      21.1  ...
106                       0.0  ...
111                       0.0  ...
112                       3.4  ...
115                       0.0  ...
117                       0.0  ...
119                       0.0  ...
121                       0.0  ...

Kysymys           Missä olet yleensä koulun välitunneilla?  \
Vastaus  Enimmäkseen ulkona, mutta silloin tällöin sisällä
Koulu_ID
101                                                   14.3
102                                                    0.0
104                                                    7.5
106                                                  100.0
111                                                   24.2
112                                                   23.3
115                                                   22.6
117                                                   29.4
119                                                   25.6
121                                                    0.0

Kysymys                                                     \
Vastaus  Enimmäkseen sisällä, mutta silloin tällöin ulkona
Koulu_ID
101                                                   62.9
102                                                   46.7
104                                                    0.0
106                                                    0.0
111                                                    9.1
112                                                    0.0
115                                                    1.9
117                                                    0.0
119                                                    0.0
121                                                    0.0

Kysymys                             \
Vastaus  Kaikki välitunnit sisällä
Koulu_ID
101                           22.9
102                           53.3
104                            1.9
106                            0.0
111                            0.0
112                            0.0
115                            0.0
117                            0.0
119                            0.0
121                            0.0

Kysymys  Koulun tilojen ja piha-alueiden suunnittelu        \
Vastaus                                        Kyllä    En
Koulu_ID
101                                             14.3  85.7
102                                             26.7  73.3
104                                             15.4  84.6
106                                            100.0   0.0
111                                             21.5  78.5
112                                             14.0  86.0
115                                             24.5  75.5
117                                             23.5  76.5
119                                             15.4  84.6
121                                             51.6  48.4

Kysymys  Välituntiliikunnan ohjaaminen muille oppilaille         \
Vastaus                                            Kyllä     En
Koulu_ID
101                                                  0.0  100.0
102                                                 13.3   86.7
104                                                 31.4   68.6
106                                                  0.0  100.0
111                                                 41.8   58.2
112                                                 18.6   81.4
115                                                 30.8   69.2
117                                                 18.8   81.2
119                                                 20.5   79.5
121                                                 37.5   62.5

Kysymys  Välituntitoiminnan suunnittelu        vuosi
Vastaus                           Kyllä     En
Koulu_ID
101                                 5.7   94.3  2022
102                                20.0   80.0  2022
104                                 0.0  100.0  2022
106                                 0.0  100.0  2022
111                                 NaN    NaN  2022
112                                20.0   80.0  2022
115                                 0.0  100.0  2022
117                                 NaN    NaN  2022
119                                31.2   68.8  2022
121                                 NaN    NaN  2022

[10 rows x 26 columns]

In [151]:
liitu_ymp2.columns.get_level_values(0).unique()

Index(['Kuinka usein käytät alla olevia paikkoja liikkumiseen kouluajan ulkopuolella vapaa-aikanasi?',
       'Koulussa oppituntien jälkeen pidettävissä liikuntakerhoissa ',
       'Koululiikunta ei innosta minua.',
       'Missä olet yleensä koulun välitunneilla?',
       'Koulun tilojen ja piha-alueiden suunnittelu',
       'Välituntiliikunnan ohjaaminen muille oppilaille',
       'Välituntitoiminnan suunnittelu', 'vuosi'],
      dtype='object', name='Kysymys')

In [12]:
# LIITU Kannustajien pivotointi

liitu_kannustajat_df.sample(3)

,Koulu_ID,Table,F_L93_AB_,Frequency,RowPercent,RowStdErr,RowLowerCL,RowUpperCL
441,140.0,Onko joku seuraavista tahoista rohkaissut ja t...,usein,3,15.789474,8.371251,0.000000,32.224336
305,159.0,Onko joku seuraavista tahoista rohkaissut ja t...,Total,131,100.000000,NaN,NaN,NaN
397,124.0,Onko joku seuraavista tahoista rohkaissut ja t...,harvoin,8,16.666667,5.382862,6.098759,27.234574

In [129]:
df = pd.DataFrame(liitu_kannustajat_df.drop_duplicates(['Koulu_ID','Table','F_L93_AB_'])).fillna('0')
df.Koulu_ID=df.Koulu_ID.astype(int)
df.Table = df.Table.str.replace(r'.*\:','',regex=True)
df.rename(columns={'Table':'Kannustaja'},inplace=True)
df.rename(columns={'F_L93_AB_':'Vastaus'},inplace=True)
df = df[(df.Vastaus != 'Total') & (df.Koulu_ID>0)]
df.RowPercent = df.RowPercent.astype(float).round(1)

liitu_kannustajat = df.pivot(columns=['Kannustaja','Vastaus'],index=['Koulu_ID'],values='RowPercent')
liitu_kannustajat['vuosi'] = vuosi

# Saving to data folder
liitu_kannustajat.to_csv("../data/liitu_kannustajat.csv")

# Sample rows
liitu_kannustajat.head(15)

Kannustaja Liikunnanopettaja                                  Luokanopettaja  \
Vastaus           ei koskaan harvoin joskus usein hyvin usein     ei koskaan
Koulu_ID
101                     57.6    24.2   15.2   0.0         3.0           60.6
102                     26.7    13.3   40.0  20.0         0.0           33.3
104                      0.0   100.0    0.0   0.0         0.0           96.2
106                    100.0     0.0    0.0   0.0         0.0          100.0
111                      NaN     NaN    NaN   NaN         NaN           95.6
112                     50.0    26.7    6.7   6.7        10.0           53.5
115                      0.0    66.7   33.3   0.0         0.0           88.5
117                      NaN     NaN    NaN   NaN         NaN          100.0
119                     25.0    31.2    0.0  25.0        18.8           73.7
121                      NaN     NaN    NaN   NaN         NaN           96.7
124                     41.7    22.9   20.8  12.5         2.1           77.4
129                     42.9    28.6   25.0   3.6         0.0           90.7
130                     27.3    22.7   36.4  13.6         0.0           74.6
134                     29.6    25.9   25.9  11.1         7.4           73.5
135                     43.8    18.8   18.8  18.8         0.0           64.7

Kannustaja                                  Kouluterveydenhoitaja tai lääkäri  \
Vastaus    harvoin joskus usein hyvin usein                        ei koskaan
Koulu_ID
101           24.2    6.1   6.1         3.0                              63.6
102            6.7   40.0  20.0         0.0                              33.3
104            1.9    1.9   0.0         0.0                              50.0
106            0.0    0.0   0.0         0.0                             100.0
111            4.4    0.0   0.0         0.0                               NaN
112           18.6   18.6   4.7         4.7                              37.9
115            7.7    3.8   0.0         0.0                               0.0
117            0.0    0.0   0.0         0.0                               NaN
119            7.9   10.5   5.3         2.6                              25.0
121            3.3    0.0   0.0         0.0                               NaN
124            8.3    8.3   3.8         2.3                              35.4
129            1.6    5.5   2.2         0.0                              35.7
130           11.9    8.5   3.4         1.7                              38.1
134            9.6   10.8   6.0         0.0                               3.6
135           17.6   11.8   0.0         5.9                              37.5

Kannustaja                                  vuosi
Vastaus    harvoin joskus usein hyvin usein
Koulu_ID
101           15.2   15.2   3.0         3.0  2022
102           20.0   26.7  13.3         6.7  2022
104            0.0   50.0   0.0         0.0  2022
106            0.0    0.0   0.0         0.0  2022
111            NaN    NaN   NaN         NaN  2022
112           34.5   13.8   6.9         6.9  2022
115           33.3   33.3  33.3         0.0  2022
117            NaN    NaN   NaN         NaN  2022
119           31.2   12.5  18.8        12.5  2022
121            NaN    NaN   NaN         NaN  2022
124           16.7   29.2  14.6         4.2  2022
129           10.7   32.1  17.9         3.6  2022
130           38.1    4.8  19.0         0.0  2022
134           14.3   25.0  42.9        14.3  2022
135           12.5   31.2  12.5         6.2  2022

In [134]:
liitu_liikku_60min.columns

Index(['a_0d', 'a_1d', 'a_2d', 'a_3d', 'a_4d', 'a_5d', 'a_6d', 'a_7d',
       'vuosi'],
      dtype='object', name='physact60')

In [14]:
# LIITU Liikkumiskyselyn pivotointi.

liitu_liikku_df.sample(3)

,Koulu_ID,F_physact60,physact60,Frequency,RowPercent,RowStdErr,RowLowerCL,RowUpperCL
281,188.0,2 päivänä,2 päivänä,4,15.384615,7.077923,1.502501,29.266730
98,124.0,Total,NaN,137,100.000000,NaN,NaN,NaN
218,159.0,2 päivänä,2 päivänä,2,1.438849,1.010363,0.000000,3.420501

In [132]:
df = liitu_liikku_df[liitu_liikku_df.physact60.fillna('').str.endswith('päivänä')].fillna('0')
df.Koulu_ID=df.Koulu_ID.astype(int)
df = df[df.Koulu_ID>0]
df.physact60='a_'+df.physact60.str[0:1]+'d'
df.RowPercent=df.RowPercent.astype(float).round(1)

liitu_liikku_60min = df.pivot(columns=['physact60'],values='RowPercent',index='Koulu_ID').fillna(0)
liitu_liikku_60min['vuosi'] = vuosi

# Saving to data folder
liitu_liikku_60min.to_csv("../data/liitu_60min.csv")

# Sample rows
liitu_liikku_60min.head(15)

physact60   a_0d  a_1d  a_2d  a_3d  a_4d  a_5d  a_6d  a_7d  vuosi
Koulu_ID
101          5.4   2.7   5.4  16.2  21.6  13.5  13.5  21.6   2022
102          0.0   0.0  13.3   6.7   0.0  26.7  13.3  40.0   2022
104          3.8   0.0   5.8  17.3   7.7   5.8   9.6  50.0   2022
106        100.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2022
111          0.0   4.5   3.0   6.0   9.0  11.9  11.9  53.7   2022
112          4.8   7.1   7.1   2.4   9.5   9.5  21.4  38.1   2022
115          0.0  11.3   9.4   9.4  13.2  20.8   3.8  32.1   2022
117          0.0   5.9   5.9  17.6  17.6   5.9   5.9  41.2   2022
119          2.6   5.1   2.6  12.8   2.6  12.8  12.8  48.7   2022
121          3.1  12.5   6.2   9.4   6.2   9.4   3.1  50.0   2022
124          0.7   2.2   3.6   6.6   9.5  18.2   8.8  50.4   2022
129          1.6   3.8   8.2  12.0   8.2   9.2  13.6  43.5   2022
130          3.4   8.6  10.3  12.1   6.9   1.7  10.3  46.6   2022
134          0.0   1.2   3.5   7.1  11.8  12.9   9.4  54.1   2022
135          0.0   5.9  17.6  11.8  17.6  23.5  11.8  11.8   2022